import {
  Hash,
  AlignLeft,
  AlignRight,
  Sigma,
  Equal,
  CircleDot,
  Percent,
  Minus,
  Plus,
} from 'lucide-react';

export const pricingPlansData = [
  {
    title: 'BASIC',
    price: '0 USD',
    period: 'Year',
    features: ['Homework Assistance', 'Smart Solution Check', 'Basic AI tutor'],
    buttonText: 'Start Now',
    recommended: false,
    className: 'bg-[#034d6e]',
  },
  {
    title: 'PREMIUM',
    price: '1200 USD',
    period: 'Year',
    features: ['Homework Assistance', 'Smart Solution Check', 'Basic AI tutor'],
    buttonText: 'Choose Premium',
    recommended: false,
    className: '',
    discount: 'Save 30 %',
  },
  {
    title: 'PRO',
    price: '1800 USD',
    period: 'Year',
    features: [
      'Homework Assistance',
      'Smart Solution Check',
      'Advanced AI tutor',
    ],
    buttonText: 'Choose Pro',
    recommended: true,
    className:
      '[background:linear-gradient(180deg,rgba(255,251,245,1)_0%,rgba(255,228,151,1)_100%)]',
  },
];

export const productSectionsData = [
  {
    title: 'AI Math Tutor',
    description: 'Solve on AI whiteboard, buddy will guide you!',
    learnMoreLink: '/products/ai-tutor',
    buttonText: 'Get Started',
    image: '/images/products/ai-tutor.png',
  },
  {
    title: 'Homework Assistant',
    description:
      'Quickly extract math questions from any assignment and learn!',
    learnMoreLink: '/products/homework-assistant',
    buttonText: 'Get Started',
    image: '/images/products/homework-assistant.png',
  },
  {
    title: 'Smart Solution Check',
    description: 'Get even your handwritten answers checked!',
    learnMoreLink: '/products/solution-check',
    buttonText: 'Get Started',
    image: '/images/products/solution-check.png',
  },
];

export const MODES = {
  TEXT: 'text',
  DRAW: 'draw',
  UPLOAD: 'upload',
};

export const FILE_TYPES = {
  IMAGE: [
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',
    'image/svg+xml',
  ],
  PDF: ['application/pdf'],
  ALL: [
    'image/jpeg',
    'image/png',
    'image/gif',
    'image/webp',
    'image/svg+xml',
    'application/pdf',
  ],
};

export const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5MB
export const MAX_FILES = 5;

export const MATH_KEYBOARD_TABS = {
  123: { icon: <Hash size={18} />, label: 'Numbers' },
  αβγ: { icon: <CircleDot size={18} />, label: 'Greek' },
  '≥≠': { icon: <Equal size={18} />, label: 'Comparisons' },
  '∈⊂': { icon: <Percent size={18} />, label: 'Set Theory' },
  'sin cos': { icon: <Minus size={18} />, label: 'Trigonometry' },
  ΣΠ: { icon: <Sigma size={18} />, label: 'Operators' },
  ΩΔ: { icon: <Plus size={18} />, label: 'Symbols' },
};

export const MATH_SYMBOLS = {
  123: [
    '+',
    '-',
    '\\times',
    '\\div',
    '=',
    '(',
    ')',
    '[',
    ']',
    '{',
    '}',
    '.',
    ',',
    '!',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '0',
  ],
  αβγ: [
    'alpha',
    'beta',
    'gamma',
    'delta',
    'epsilon',
    'zeta',
    'eta',
    'theta',
    'iota',
    'kappa',
    'lambda',
    'mu',
    'nu',
    'xi',
    'omicron',
    'pi',
    'rho',
    'sigma',
    'tau',
    'upsilon',
    'phi',
    'chi',
    'psi',
    'omega',
  ],
  '≥≠': [
    ['<', '<'],
    ['>', '>'],
    ['leq', '≤'],
    ['geq', '≥'],
    ['neq', '≠'],
    ['approx', '≈'],
    ['equiv', '≡'],
    ['cong', '≅'],
    ['sim', '∼'],
    ['simeq', '≃'],
    ['propto', '∝'],
  ],
  '∈⊂': [
    ['in', '∈'],
    ['notin', '∉'],
    ['subset', '⊂'],
    ['supset', '⊃'],
    ['subseteq', '⊆'],
    ['supseteq', '⊇'],
    ['cap', '∩'],
    ['cup', '∪'],
    ['setminus', '\\'],
    ['emptyset', '∅'],
    ['forall', '∀'],
    ['exists', '∃'],
    ['nexists', '∄'],
  ],
  'sin cos': [
    'sin',
    'cos',
    'tan',
    'sec',
    'csc',
    'cot',
    'arcsin',
    'arccos',
    'arctan',
    'sinh',
    'cosh',
    'tanh',
  ],
  ΣΠ: [
    { type: 'frac', display: '□\n―\n□' },
    { type: 'exponent', display: '□²' },
    { type: 'exponent', display: 'x□' },
    { type: 'sqrt', display: '√□' },
    { type: 'nthroot', display: '□√□' },
    { type: 'log', display: 'log□' },
    { type: 'pi', display: 'π' },
    { type: 'infty', display: '∞' },
    { type: 'integral', display: '∫' },
    { type: 'sum', display: 'Σ' },
    { type: 'product', display: 'Π' },
    { type: 'limit', display: 'lim x→□' },
    { type: 'times', display: '×' },
    { type: 'div', display: '÷' },
    { type: 'subscript', display: 'x□' },
  ],
  ΩΔ: [
    'Gamma',
    'Delta',
    'Theta',
    'Lambda',
    'Xi',
    'Pi',
    'Sigma',
    'Phi',
    'Psi',
    'Omega',
    'nabla',
    'partial',
    'hbar',
    'imath',
    'jmath',
  ],
};
